[workspace]
members = [
    "crates/cp0-appd",
    "crates/cp0-audio-protocol",
    "crates/cp0-audiod",
    "crates/cp0-camera-protocol",
    "crates/cp0-camerad",
    "crates/cp0-document-protocol",
    "crates/cp0-documentd",
    "crates/cp0-gpio-protocol",
    "crates/cp0-gpiod",
    "crates/cp0-manifest",
    "crates/cp0-network-protocol",
    "crates/cp0-networkd",
    "crates/cp0-package",
    "crates/cp0-radio-protocol",
    "crates/cp0-radiod",
    "crates/cp0-storage-protocol",
    "crates/cp0-storaged",
    "crates/cp0-store-protocol",
    "crates/cp0-stored",
    "crates/cp0ctl",
    "sdk/rust",
]
resolver = "2"

[workspace.package]
edition = "2024"
rust-version = "1.85"

[workspace.dependencies]
libc = "0.2.177"
serde = { version = "1.0.228", features = ["derive"] }
serde_json = "1.0.150"
ed25519-dalek = "2.2.0"
sha2 = "0.10.9"
semver = "1.0.27"

[profile.release]
codegen-units = 1
lto = "thin"
opt-level = "s"
panic = "abort"
strip = true
