[package]
name = "cp0-stored"
version = "0.1.0"
edition.workspace = true
rust-version.workspace = true

[dependencies]
cp0-appd = { path = "../cp0-appd" }
cp0-networkd = { path = "../cp0-networkd" }
cp0-package = { path = "../cp0-package" }
cp0-store-protocol = { path = "../cp0-store-protocol" }
libc.workspace = true
sha2.workspace = true
ureq = { version = "=3.3.0", default-features = false, features = ["rustls"] }
