d /run/cardputerzero-appd 0750 root cp0-control -
d /run/cardputerzero-appd/store 0700 cp0-store cp0-store -
d /run/cardputerzero-broker 0711 root root -
d /run/cardputerzero-networkd 0755 root root -
d /run/cardputerzero-documentd 0755 root root -
d /run/cardputerzero-audiod 0755 root root -
d /run/cardputerzero-camerad 0755 root root -
d /run/cardputerzero-gpiod 0755 root root -
d /run/cardputerzero-radiod 0755 root root -
d /run/cardputerzero-storaged 0755 root root -
d /run/cardputerzero-store 0750 root cp0-control -
