d /etc/cardputerzero 0755 root root -
d /etc/cardputerzero/trust 0755 root root -
d /etc/cardputerzero/trust/store 0755 root root -
d /etc/cardputerzero/trust/developers 0755 root root -
d /etc/cardputerzero/trust/revoked 0755 root root -
