PermitRootLogin no
AllowGroups cp0-ssh cp0-developer-access
PasswordAuthentication yes
KbdInteractiveAuthentication no
PubkeyAuthentication yes
AuthorizedKeysFile /etc/cardputerzero/authorized_keys/%u
DisableForwarding yes
UsePAM yes
