[package]
name = "cp0-devd"
version = "0.1.0"
edition.workspace = true
rust-version.workspace = true
publish = false

[dependencies]
base64.workspace = true
cp0-appd = { path = "../cp0-appd" }
cp0-manifest = { path = "../cp0-manifest" }
cp0-package = { path = "../cp0-package" }
cp0-provision-protocol = { path = "../cp0-provision-protocol" }
libc.workspace = true
serde.workspace = true
serde_json.workspace = true
sha2.workspace = true
