[server]
host-name=cardputerzero-maintenance
use-ipv4=yes
use-ipv6=yes
allow-point-to-point=no
cache-entries-max=128
ratelimit-interval-usec=1000000
ratelimit-burst=100

[wide-area]
enable-wide-area=no

[publish]
publish-addresses=yes
publish-hinfo=no
publish-workstation=no
publish-domain=no

[reflector]
enable-reflector=no
